name: build

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:

  setup-and-compile:
    needs: setup
    runs-on: ubuntu-latest
    name: "configuracion y compilacion con Gradle"
    steps:
      - uses: actions/checkout@v2
      - name: Compilacion gradle
        run: |
          chmod +x gradlew
          ./gradlew build -x test compileTestJava --info
