name: Compilacion

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  compile:
    runs-on: ubuntu-latest
    name: "Compilacion con Gradle"
    steps:
      - uses: actions/checkout@v2
      - name: Compilacion gradle
        run: |
          chmod +x gradlew
          ./gradlew build -x test compileTestJava --info